[package]
name = "board_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "board_generator"
crate-type = ["cdylib"]

[dependencies]
array2d = "0.3.2"
pyo3 = "0.20.0"
rand = "0.8.5"
